[tool.poetry]
name = "buscape"
version = "0.1.0"
description = "Buscapé Scraper"
authors = ["Marcuth <example@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.0"
parsel = "^1.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
